
aws:
  accessKey: ${AWS_ACCESSKEY}
  secretAccessKey: ${AWS_SECRETACCESSKEY}
  bucketName: ${AWS_BUCKETNAME}
  region: ${AWS_REGION}

spring:
  application:
    name: CORE-UTILS
  config:
    import: "optional:file:../.env[.properties]"
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS}

resilience4j:
  circuitbreaker:
    instances:
      ONLINESHOP-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
retry:
  maxAttempts: 3
  waitDuration: 2 #value in seconds
