spring:
  application:
    name: ONLINESHOP-SERVICE
  config:
    import: "optional:configserver:http://localhost:8888", "file:../../../.env[.properties]"

resilience4j:
  circuitbreaker:
    instances:
      ONLINESHOP-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
retry:
  maxAttempts: 3
  waitDuration: 2 #value in seconds
