FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY /target/os-service-registry-0.0.1-SNAPSHOT.jar /app/os-service-registry-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar", "/app/os-service-registry-0.0.1-SNAPSHOT.jar"]